import { LangLayoutModel } from './interfaces';

export const engLayout: LangLayoutModel = {
	lang: 'RU',
	author1: 'Anton Romanovich',
	author2: 'Sasha Afanasienka',
	homeTitle: 'Kanban board for teams to organize their work',
	homeDescription: 'Collaborate, manage projects, and reach new productivity peaks. Accomplish it all with RS Project Management App',
	teamTitle: 'Our team',
	technologiesTitle: 'Our technologies',
	homeBtn: 'Get Started',
	homeBtnBoards: 'Go to boards',
	navProfile: 'Profile',
	navBoards: 'Boards',
	navHome: 'Home',
	singIn: 'Sign In',
	singUp: 'Sign Up',
	singOut: 'Sing Out',
	register: 'Register',
	noAccount: "Don't have an account yet? ",
	hasAccount: 'Already have an account? ',
	name: 'Name',
	login: 'Login',
	password: 'Password',
	addBoardBtn: 'Add Board',
	addColumnBtn: 'Add Column',
	addTaskBtn: 'Add Task',
	createBoardHeader: 'Create Board',
	updateBoardHeader: 'Update Board',
	createTaskHeader: 'Create Task',
	createColumnHeader: 'Add Column',
	createNewFormTitle: 'Title',
	createNewFormDescr: 'Description',
	addBtn: 'Add',
	confirmBtn: 'Confirm',
	cancelBtn: 'Cancel',
	deleteBtn: 'Delete',
	updateBtn: 'Update',
	changeUser: 'Change User',
	assignTo: 'Assigned To: ',
	confirmation: 'Are you sure? That action cannot be undone',
	confirmationDeleteBoard: 'Are you sureto delete the board',
	confirmationDeleteTask: 'Are you sureto delete the task',
	confirmationDeleteColumn: 'Are you sureto delete the column',
	confirmationDescription: 'That action cannot be undone',
	deleteColumn: 'Column and assigned tasks will be deleted',
	deleteTask: 'Task will be deleted',
	deleteBoard: 'Board and assigned tasks will be deleted',
	deleteUser: 'This account will be deleted',
	successCreated: 'Successfully Created',
	successDeleted: 'Successfully Deleted',
	editProfile: 'Edit Profile',
	singUpGreet: 'Hello',
	singUpMessage: 'Please create an account and we are set to go',
	singInGreet: 'Welcome back',
	singInMessage: 'Please sign in to go back to work',
	toastSuccessLogIn: 'Congrats! You are successfully logged in',
	toastFailureLogIn: 'Authorization error. Please make sure you have an account or check your login and password',
	toastSuccessSignUp: 'welcome! Please Log In to proceed!',
	toastFailureSignUpHasAccount: 'You already have an account, please sign in',
	toastFailureSignUp: 'Authorization error! Please try again',
	toastProfileUpdatedSuccess: 'account has been updated. PLease sign in to proceed',
	toastProfileUpdatedFailureLogin: 'Error! User with such login already exists',
	toastProfileUpdatedFailure: 'Authorization error! Please try again',
	toastDeleteUserSuccess: 'Account has been deleted',
	toastDeleteUserFailure: 'A server error has occured',
	notFound: 'Page was not found',
	errorBoundary: 'Ooops.. Something went wrong',
	ownerText: 'Owner',
	taskIdText: 'Task ID',
	toastUnknownError: 'Unknown Error! Try to refresh the page',
	boardTxt: 'Board',
	columnTxt: 'Column',
	taskTxt: 'Task',
	userTxt: 'User',
	scsCreated: 'successfully created',
	scsDeleted: 'successfully deleted',
	scsUpdated: 'successfully updated',
	usrDeleted: 'successfully deleted',
	usrUpdated: 'successfully deleted',
	errorOccured: 'An error has occured:',
	cannotDelete: 'You cannot delete/edit boards you have been invited to',
	successfullyLogged: 'Succesfully logged in',
	successfullyRegistered: 'welcome! Please Log In to proceed!',
	somethingWrong: 'Ooops.. Something went wrong',
	logoText: 'Project management app',
	noTitleText: 'No title',
	noDescriptionText: 'No description',
	invitedUsersText: 'Invite users: ',
	filterAllBoards: 'All',
	filterOwnBoards: 'Own boards',
	filterGuestBoards: 'Guest boards',
};

export const rusLayout: LangLayoutModel = {
	lang: 'EN',
	author1: 'Антон Романович',
	author2: 'Саша Афанасенко',
	homeTitle: 'Бесконечные Канбан-доски для организации командной работы',
	homeDescription: 'Управляйте проектами и командами и достигайте новых вершин продуктивности с помощью RS Project Management App',
	teamTitle: 'Наша команда',
	technologiesTitle: 'Наши технологии',
	homeBtn: 'Начать',
	homeBtnBoards: 'К доскам',
	navProfile: 'Профиль',
	navBoards: 'Доски',
	navHome: 'Главная',
	singIn: 'Войти',
	singUp: 'Регистрация',
	singOut: 'Выйти',
	register: 'Зарегистрироваться',
	noAccount: 'Еще нет аккаунта? ',
	hasAccount: 'Уже есть аккаунт? ',
	name: 'Имя',
	login: 'Логин',
	password: 'Пароль',
	addBoardBtn: 'Добавить доску',
	addColumnBtn: 'Добавить колонку',
	addTaskBtn: 'Добавить задачу',
	createBoardHeader: 'Создание доски',
	updateBoardHeader: 'Обновление доски',
	createTaskHeader: 'Создание задачи',
	createColumnHeader: 'Создание колонки',
	createNewFormTitle: 'Название',
	createNewFormDescr: 'Описание',
	addBtn: 'Добавить',
	confirmBtn: 'Подтвердить',
	cancelBtn: 'Отменить',
	deleteBtn: 'Удалить',
	updateBtn: 'Обновить',
	changeUser: 'Сменить пользователя',
	assignTo: 'Назначена: ',
	confirmation: 'Вы уверены? Упущенного не вернуть назад',
	confirmationDeleteBoard: 'Вы уверены, что хотите удалить доску',
	confirmationDeleteTask: 'Вы уверены, что хотите удалить задачу',
	confirmationDeleteColumn: 'Вы уверены, что хотите удалить задачу',
	confirmationDescription: 'Упущенного не вернуть назад',
	deleteColumn: 'Колонка и все привязанные задачи будут удалены',
	deleteTask: 'Задача будет удалена',
	deleteBoard: 'Доска и все привязанные задачи будут удалены',
	deleteUser: 'Аккаунт будет удален',
	successCreated: 'Создано',
	successDeleted: 'Удалено',
	editProfile: 'Редактировать профиль',
	singUpGreet: 'Здравствуйте',
	singUpMessage: 'Создать аккаунт - все что требуется для старта',
	singInGreet: 'С возвращением',
	singInMessage: 'Пожалуйста, авторизируйтесь, чтобы вернуться к работе',
	toastSuccessLogIn: 'Ура! Вход в аккаунт выполнен!',
	toastFailureLogIn: 'Ошибка авторизации. Проверьте введенные данные или зарегистрируйтесь',
	toastSuccessSignUp: 'добро пожаловать! Пожалуйста, выполните вход в аккаунт!',
	toastFailureSignUpHasAccount: 'У вас уже есть аккаунт, пожалуйста авторизируйтесь',
	toastFailureSignUp: 'Ошибка авторизации! Пожалуйста, поробуйте снова',
	toastProfileUpdatedSuccess: 'данные аккаунта обновлены. Пожалуйста, авторизируйтесь с новыми данными',
	toastProfileUpdatedFailureLogin: 'Пользователь с таким аккаунтом уже существует',
	toastProfileUpdatedFailure: 'Ошибка авторизации! Пожалуйста, поробуйте снова',
	toastDeleteUserSuccess: 'Аккаунт был удален',
	toastDeleteUserFailure: 'Ошибка сервера, пожалуйста попробуйте снова',
	notFound: 'страница не найдена',
	errorBoundary: 'Упс... Что-то пошло не так',
	ownerText: 'Владелец',
	taskIdText: 'ID задачи',
	toastUnknownError: 'Ерунда какая-то, попробуйте перезагрузить страницу!',
	boardTxt: 'Доска',
	columnTxt: 'Колонка',
	taskTxt: 'Задача',
	userTxt: 'Пользователь',
	scsCreated: 'успешно создана',
	scsDeleted: 'успешно удалена',
	scsUpdated: 'успешно обновлена',
	usrDeleted: 'успешно удален',
	usrUpdated: 'успешно обновлен',
	errorOccured: 'Ошибка:',
	cannotDelete: 'Нельзя удалять чужую доску',
	successfullyLogged: 'Вы успешно вошли',
	successfullyRegistered: 'привет! Войдите на сайт чтобы продолжить',
	somethingWrong: 'Упс... Что-то пошло не так',
	logoText: 'Управление проектами',
	noTitleText: 'Нет название',
	noDescriptionText: 'Нет Описания',
	invitedUsersText: 'Приласить пользователей: ',
	filterAllBoards: 'Все',
	filterOwnBoards: 'Свои доски',
	filterGuestBoards: 'Чужие доски',
};
