export const engLayout = {
  lang: "RU",
  homeTitle: 'Kanban board for teams to organize their work',
  homeDescription: "Collaborate, manage projects, and reach new productivity peaks. Accomplish it all with RS Project Management App",
  homeBtn: 'Get Started',
  navProfile: 'Profile',
  navBoards: 'Boards',
  singIn: 'Sign In',
  singUp: 'Sign Up',
  register: 'Register',
  noAccount: "Don't have an account yet?",
  hasAccount: 'Already have an account?',
  name: 'Name',
  login: 'Login',
  password: 'Password',
  addBoardBtn: "Add Board",
  addColumnBtn: 'Add Column',
  addTaskBtn: 'Add Task',
  createBoardHeader: 'Create Board',
  createTaskHeader: 'Create Task',
  createColumnHeader: 'Add Column',
  createNewFormTitle: 'Title',
  createNewFormDescr: 'Description',
  addBtn: 'Add',
  confirmBtn: 'Confirm',
  cancelBtn: 'Cancel',
  deleteBtn: 'Delete',
  changeUser: 'Change User',
  assignTo: 'Assigned To: ',
  confirmation: 'Are you sure?',
  deleteColumn: 'Column and assigned tasks will be deleted',
  deleteTask: 'Task will be deleted',
  deleteBoard: 'Board and assigned tasks will be deleted',
  successCreated: 'Successfully Created',
  successDeleted: 'Successfully Deleted',
}

export const rusLayout = {
  lang: "EN",
  homeTitle: 'Бесконечные Канбан-доски для организации командной работы',
  homeDescription: "Управляйте проектами и командами и достигайте новых вершин продуктивности с помощью RS Project Management App",
  homeBtn: 'Начать',
  navProfile: 'Профиль',
  navBoards: 'Доски',
  singIn: 'Войти',
  singUp: 'Регистрация',
  register: 'Зарегистрироваться',
  noAccount: "Еще нет аккаунта?",
  hasAccount: 'Уже есть аккаунт',
  name: 'Имя',
  login: 'Логин',
  password: 'Пароль',
  addBoardBtn: "Добавить доску",
  addColumnBtn: 'Добавить колонку',
  addTaskBtn: 'Добавить задачу',
  createBoardHeader: 'Создание доски',
  createTaskHeader: 'Создание задачи',
  createColumnHeader: 'Создание колонки',
  createNewFormTitle: 'Название',
  createNewFormDescr: 'Описание',
  addBtn: 'Добавить',
  confirmBtn: 'Подтвердить',
  cancelBtn: 'Отменить',
  deleteBtn: 'Удалить',
  changeUser: 'Сменить пользователя',
  assignTo: 'Назначена: ',
  confirmation: 'Вы уверены?',
  deleteColumn: 'Колонка и все привязанные задачи будут удалены',
  deleteTask: 'Задача будет удалена',
  deleteBoard: 'Доска и все привязанные задачи будут удалены',
  successCreated: 'Создано',
  successDeleted: 'Удалено',
}