import { LangLayoutModel } from './interfaces';

export const engLayout: LangLayoutModel = {
	lang: 'RU',
	author1: 'Anton Romanovich',
	author2: 'Sasha Afanasienka',
	homeTitle: 'Kanban board for teams to organize their work',
	homeDescription: 'Collaborate, manage projects, and reach new productivity peaks. Accomplish it all with RS Project Management App',
	teamTitle: 'Our team',
	technologiesTitle: 'Our technologies',
	homeBtn: 'Get Started',
	homeBtnBoards: 'Go to boards',
	navProfile: 'Profile',
	navBoards: 'Boards',
	navHome: 'Home',
	singIn: 'Sign In',
	singUp: 'Sign Up',
	singOut: 'Sing Out',
	register: 'Register',
	noAccount: "Don't have an account yet? ",
	hasAccount: 'Already have an account? ',
	name: 'Name',
	login: 'Login',
	password: 'Password',
	addBoardBtn: 'Add Board',
	addColumnBtn: 'Add Column',
	addTaskBtn: 'Add Task',
	createBoardHeader: 'Create Board',
	createTaskHeader: 'Create Task',
	createColumnHeader: 'Add Column',
	createNewFormTitle: 'Title',
	createNewFormDescr: 'Description',
	addBtn: 'Add',
	confirmBtn: 'Confirm',
	cancelBtn: 'Cancel',
	deleteBtn: 'Delete',
	changeUser: 'Change User',
	assignTo: 'Assigned To: ',
	confirmation: 'Are you sure? That action cannot be undone',
	deleteColumn: 'Column and assigned tasks will be deleted',
	deleteTask: 'Task will be deleted',
	deleteBoard: 'Board and assigned tasks will be deleted',
	deleteUser: 'This account will be deleted',
	successCreated: 'Successfully Created',
	successDeleted: 'Successfully Deleted',
	editProfile: 'Edit Profile',
	singUpGreet: 'Hello',
	singUpMessage: 'Please create an account and we are set to go',
	singInGreet: 'Welcome back',
	singInMessage: 'Please sign in to go back to work',
	toastSuccessLogIn: 'Congrats! You are successfully logged in',
	toastFailureLogIn: 'Authorization error. Please make sure you have an account or check your login and password',
	toastSuccessSignUp: 'welcome! Please Log In to proceed!',
	toastFailureSignUpHasAccount: 'You already have an account, please sign in',
	toastFailureSignUp: 'Authorization error! Please try again',
	toastProfileUpdatedSuccess: 'account has been updated. PLease sign in to proceed',
	toastProfileUpdatedFailureLogin: 'Error! User with such login already exists',
	toastProfileUpdatedFailure: 'Authorization error! Please try again',
	toastDeleteUserSuccess: 'Account has been deleted',
	toastDeleteUserFailure: 'A server error has occured',
	notFound: 'Page was not found',
};

export const rusLayout: LangLayoutModel = {
	lang: 'EN',
	author1: 'Антон Романович',
	author2: 'Саша Афанасенко',
	homeTitle: 'Бесконечные Канбан-доски для организации командной работы',
	homeDescription: 'Управляйте проектами и командами и достигайте новых вершин продуктивности с помощью RS Project Management App',
	teamTitle: 'Наша команда',
	technologiesTitle: 'Наши технологии',
	homeBtn: 'Начать',
	homeBtnBoards: 'К доскам',
	navProfile: 'Профиль',
	navBoards: 'Доски',
	navHome: 'Главная',
	singIn: 'Войти',
	singUp: 'Регистрация',
	singOut: 'Выйти',
	register: 'Зарегистрироваться',
	noAccount: 'Еще нет аккаунта? ',
	hasAccount: 'Уже есть аккаунт? ',
	name: 'Имя',
	login: 'Логин',
	password: 'Пароль',
	addBoardBtn: 'Добавить доску',
	addColumnBtn: 'Добавить колонку',
	addTaskBtn: 'Добавить задачу',
	createBoardHeader: 'Создание доски',
	createTaskHeader: 'Создание задачи',
	createColumnHeader: 'Создание колонки',
	createNewFormTitle: 'Название',
	createNewFormDescr: 'Описание',
	addBtn: 'Добавить',
	confirmBtn: 'Подтвердить',
	cancelBtn: 'Отменить',
	deleteBtn: 'Удалить',
	changeUser: 'Сменить пользователя',
	assignTo: 'Назначена: ',
	confirmation: 'Вы уверены? Упущенного не вернуть назад',
	deleteColumn: 'Колонка и все привязанные задачи будут удалены',
	deleteTask: 'Задача будет удалена',
	deleteBoard: 'Доска и все привязанные задачи будут удалены',
	deleteUser: 'Аккаунт будет удален',
	successCreated: 'Создано',
	successDeleted: 'Удалено',
	editProfile: 'Редактировать профиль',
	singUpGreet: 'Здравствуйте',
	singUpMessage: 'Создать аккаунт - все что требуется для старта',
	singInGreet: 'С возвращением',
	singInMessage: 'Пожалуйста, авторизируйтесь, чтобы вернуться к работе',
	toastSuccessLogIn: 'Ура! Вход в аккаунт выполнен!',
	toastFailureLogIn: 'Ошибка авторизации. Проверьте введенные данные или зарегистрируйтесь',
	toastSuccessSignUp: 'добро пожаловать! Пожалуйста, выполните вход в аккаунт!',
	toastFailureSignUpHasAccount: 'У вас уже есть аккаунт, пожалуйста авторизируйтесь',
	toastFailureSignUp: 'Ошибка авторизации! Пожалуйста, поробуйте снова',
	toastProfileUpdatedSuccess: 'данные аккаунта обновлены. Пожалуйста, авторизируйтесь с новыми данными',
	toastProfileUpdatedFailureLogin: 'Пользователь с таким аккаунтом уже существует',
	toastProfileUpdatedFailure: 'Ошибка авторизации! Пожалуйста, поробуйте снова',
	toastDeleteUserSuccess: 'Аккаунт был удален',
	toastDeleteUserFailure: 'Ошибка сервера, пожалуйста попробуйте снова',
	notFound: 'страница не найдена',
};
