import Head from 'next/head';
import Header from '../../components/header/header';
import Footer from '../../components/footer/footer';

const Home = () => (
	<>
		<Head>
			<title>Home page</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<Header></Header>
		<Footer></Footer>
	</>
);

export default Home;
